<a href="https://colab.research.google.com/github/IbrahimSayyad2001/Assignment-python-1/blob/main/pandas2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
st=pd.read_csv('/content/StudentsPerformance.csv')

In [5]:
st.to_excel('ibrahim.xlsx')
st

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [6]:
st.dtypes

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

In [9]:
st['math score'].dtypes

dtype('int64')

In [11]:
st['new math score']=st['math score'].astype('float')

In [13]:
st.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score', 'new math score'],
      dtype='object')

In [15]:
st['race/ethnicity'].unique()

array(['group B', 'group C', 'group A', 'group D', 'group E'],
      dtype=object)

In [19]:
st[['race/ethnicity', 'parental level of education', 'lunch']].value_counts()

race/ethnicity  parental level of education  lunch
group C         associate's degree           standard        56
                some college                 standard        46
group D         some college                 standard        41
group C         high school                  standard        41
group D         some high school             standard        37
group B         high school                  standard        32
group D         associate's degree           standard        29
                high school                  standard        28
group E         some college                 standard        28
group B         some high school             standard        28
group C         some high school             standard        28
group B         associate's degree           standard        27
group E         associate's degree           standard        26
group D         some college                 free/reduced    26
group C         bachelor's degree            standard        25
                some college                 free/reduced    23
                high school                  free/reduced    23
                associate's degree           free/reduced    22
                some high school             free/reduced    21
group B         some college                 standard        21
group D         associate's degree           free/reduced    21
                master's degree              standard        18
                high school                  free/reduced    16
group B         high school                  free/reduced    16
                some college                 free/reduced    16
group C         bachelor's degree            free/reduced    15
group D         bachelor's degree            free/reduced    14
                                             standard        14
group B         associate's degree           free/reduced    14
group E         bachelor's degree            standard        14
                high school                  standard        14
group D         some high school             free/reduced    13
group A         some high school             standard        13
group E         associate's degree           free/reduced    13
                some high school             standard        12
group B         bachelor's degree            standard        11
group A         some high school             free/reduced    11
                some college                 standard        11
                high school                  standard        11
group C         master's degree              free/reduced    10
group B         some high school             free/reduced    10
group A         bachelor's degree            standard        10
group C         master's degree              standard         9
group B         bachelor's degree            free/reduced     9
group E         high school                  free/reduced     8
group A         associate's degree           standard         7
group E         some college                 free/reduced     7
group A         high school                  free/reduced     7
                associate's degree           free/reduced     7
                some college                 free/reduced     7
group E         some high school             free/reduced     6
                master's degree              standard         5
group D         master's degree              free/reduced     5
group B         master's degree              free/reduced     4
group E         bachelor's degree            free/reduced     4
                master's degree              free/reduced     3
group A         master's degree              free/reduced     2
group B         master's degree              standard         2
group A         bachelor's degree            free/reduced     2
                master's degree              standard         1
dtype: int64

In [22]:
st.gender.map({'male':1,'female':2})

0      2
1      2
2      2
3      1
4      1
      ..
995    2
996    1
997    2
998    2
999    2
Name: gender, Length: 1000, dtype: int64

In [23]:
st.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score', 'new math score'],
      dtype='object')

In [24]:
st.drop(columns=[  'writing score', 'new math score'])

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score
0,female,group B,bachelor's degree,standard,none,72,72
1,female,group C,some college,standard,completed,69,90
2,female,group B,master's degree,standard,none,90,95
3,male,group A,associate's degree,free/reduced,none,47,57
4,male,group C,some college,standard,none,76,78
...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99
996,male,group C,high school,free/reduced,none,62,55
997,female,group C,high school,free/reduced,completed,59,71
998,female,group D,some college,standard,completed,68,78
999,female,group D,some college,free/reduced,none,77,86

In [26]:
st.insert(3,column='good',value=range(1000))

In [27]:
st.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'good',
       'lunch', 'test preparation course', 'math score', 'reading score',
       'writing score', 'new math score'],
      dtype='object')